name: Custom Action Docker
on:
  push:
    branches:
      - master
jobs:
  sample-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sample Python project
        uses: ./.github/actions/python-hello-world
