name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file actions/python-hello-world/Dockerfile --tag python-hello-world
    - name: Run the docker image
      run: docker run --rm python-hello-world
