name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file actions/python-hello-world/Dockerfile --tag python-hello-world
    - name: Run the docker image
      run: docker run --rm python-hello-world
    - name: Checking the default environment variable
      run: echo "Testing the default environment variable $GITHUB_REF"
    - name: Checking the custom environment variable
      run: echo "Testing the custom environment variable $first_name"
      env:
        first_name: Shashi
